package es.tributasenasturias.services.autenticacion;

import javax.annotation.Resource;
import javax.jws.HandlerChain;
import javax.jws.WebService;
import javax.xml.ws.BindingType;
import javax.xml.ws.Holder;
import javax.xml.ws.WebServiceContext;

import es.tributasenasturias.services.autenticacion.soap.Constantes;
import es.tributasenasturias.services.autenticacion.soap.GeneradorIdSesion;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */
@WebService(portName = "WSAutenticacionEPSTSOAP", serviceName = "WSAutenticacionEPST", targetNamespace = "http://services.tributasenasturias.es/WSAutenticacionEPST/", wsdlLocation = "/wsdls/WSAutenticacionEPST.wsdl", endpointInterface = "es.tributasenasturias.services.autenticacion.WSAutenticacionEPST")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
@HandlerChain(file="HandlerChain.xml")
public class WSAutenticacionEPST_WSAutenticacionEPSTSOAPImpl implements
		WSAutenticacionEPST {

	@Resource
	private WebServiceContext context;
	public WSAutenticacionEPST_WSAutenticacionEPSTSOAPImpl() {
	}

	/**
	 * 
	 * @param tiposAdmitidos
	 * @param resultado
	 * @param informacionCertificado
	 * @param certificado
	 */
	public void validacionCertificado(byte[] certificado, TiposAdmitidosType tiposAdmitidos,
			Holder<InformacionCertificadoType> informacionCertificado,
			Holder<ResultadoType> resultado) {
		//Se recupera id de sesión.
		String idSesion="";
		if (context.getMessageContext().containsKey(Constantes.ID_SESION))
		{
			idSesion=(String)context.getMessageContext().get(Constantes.ID_SESION);
		}
		else
		{
			idSesion=GeneradorIdSesion.generaIdSesion();
		}
		AutenticacionEPST autenticacion = new AutenticacionEPST(idSesion);
		autenticacion.validacionCertificado(certificado, tiposAdmitidos, informacionCertificado, resultado);
		return;
	}

}
